const REGISTER_USER = 'CREATE_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const LOGIN_USER = 'LOGIN_USER';
const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';

const LOAD_USERS = 'LOAD_USERS';
const MAKE_USERS_ADMIN = 'MAKE_USERS_ADMIN';
const DELETE_USERS = 'DELETE_USERS';

const LOAD_TASKS = 'LOAD_TASKS';
const INITIALIZE_TASK_FOR_EDITING = 'INITIALIZE_TASK_FOR_EDITING';
const DESTROY_TASK_FOR_EDITING = 'DESTROY_TASK_FOR_EDITING';
const APPLY_TASK_CHANGES = 'APPLY_TASK_CHANGES';
const DELETE_TASK = 'DELETE_TASK';
const ADD_NEW_TASK = 'ADD_NEW_TASK';

const OPEN_NEW_TASK_DIALOG = 'OPEN_NEW_TASK_DIALOG';
const CLOSE_NEW_TASK_DIALOG = 'CLOSE_NEW_TASK_DIALOG';

export {
    REGISTER_USER, LOGOUT_USER, LOGIN_USER, LOAD_USERS, MAKE_USERS_ADMIN,
    DELETE_USERS, LOAD_TASKS, INITIALIZE_TASK_FOR_EDITING, DESTROY_TASK_FOR_EDITING,
    APPLY_TASK_CHANGES, DELETE_TASK, CLOSE_NEW_TASK_DIALOG, OPEN_NEW_TASK_DIALOG, IS_USER_LOGGED_IN,
    ADD_NEW_TASK
};
