const REGISTER_USER = 'CREATE_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const LOGIN_USER = 'LOGIN_USER';

const LOAD_USERS = 'LOAD_USERS';
const MAKE_USERS_ADMIN = 'MAKE_USERS_ADMIN';
const DELETE_USERS = 'DELETE_USERS';

const LOAD_TASKS = 'LOAD_TASKS';

export {REGISTER_USER, LOGOUT_USER, LOGIN_USER, LOAD_USERS, MAKE_USERS_ADMIN, DELETE_USERS, LOAD_TASKS};